blog/urls.py
from django.conf.urls import url
from blog import views 

urlpatterns = [
	url(r'^$',views.index,name='home'),
	url(r'^category_detail/',views.category_detail,name='category_detail'),
	url(r'^article_detail/',views.article_detail,name='article_detail'),
]

insCms/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
#coding:utf-8
from __future__ import unicode_literals

from django.db import models
from DjangoUeditor.models import UEditorField

# Create your models here.
class Category(models.Model):
	name = models.CharField('分类名称',max_length=256)
	desc = models.CharField('分类描述',max_length=512)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = '分类'
		verbose_name_plural = '分类'

class Article(models.Model):
	category = models.ManyToManyField(Category,verbose_name='分类')

	title = models.CharField('标题',max_length=256)
	author = models.ForeignKey('auth.User',blank=True,null=True,verbose_name='作者')
	pub_date = models.DateTimeField('发布时间',auto_now_add=True,editable=True)
	mod_date = models.DateTimeField('更新时间',auto_now=True,null=True)
	content = UEditorField('内容', height=300, width=1000,
        		default=u'', blank=True, imagePath="uploads/images/",
        		toolbars='besttome', filePath='uploads/files/')
	views = models.IntegerField('阅读次数',default=1)

	published = models.BooleanField('正式发布',default=True)

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name = '文章'
		verbose_name_plural = '文章'

blog/views.py
from django.shortcuts import render, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.models import Category, Article

# Create your views here.
def index(request):
	categorys = Category.objects.all()
	articles = Article.objects.all().filter(published=True).order_by('-id')
	paginator = Paginator(articles,5)
	page = request.GET.get('page')
	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)

	ctx = {
		'categorys': categorys,
		'articles': articles,
	}

	return render(request,'blog/index.html',ctx)

def category_detail(request):
	categ_id = request.GET.get('id',1)
	category = Category.objects.get(pk=categ_id)
	articles = Article.objects.filter(category=category,published=True).order_by('-id')
	paginator = Paginator(articles,3)
	page = request.GET.get('page')
	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)
	ctx = {
		'category': category,
		'articles': articles,
	}

	return render(request,'blog/category_detail.html',ctx)

def article_detail(request):
	article_id = request.GET.get('id',1)
	article = Article.objects.get(pk=article_id)
	article.views += 1
	article.save()
	ctx = {
		'article': article,
	}

	return render(request,'blog/article_detail.html',ctx)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <!--[if lt IE 9]>
			<script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
{% block header %}
<!-- header -->
<header class="jumbotron subhead" id="header-base">
    <div class="container">
        <h1>insCms</h1>
        <h3>&emsp;&emsp;The quiter you become,the more you are able to hear...</h3>
    </div>
</header>
<!-- /.header -->
{% endblock %}

<!-- main part -->
{% block content %}{% endblock %}
<!-- /.main -->

<!-- footer -->
<footer class="footer" role="contentinfo">
    <hr>
    <div class="container">
        <p class="text-center"><strong>insCms</strong>-Ins©All rights reserved</p>
        <h5 class="text-center"> Powered by&nbsp;<a href="#">Ins</a></h5>
    </div>
</footer>
<!-- /.footer-->
<!-- core JavaScript================================================== -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" left="92%" bottom="5%" text="返回顶部" src="{% static 'js/x-return-top.min.js' %}"></script>

<script type="text/javascript">
    $('#{{active_menu}}').addClass("active");
</script>
<!-- /core JavaScript================================================== -->
</body>
</html>

templates/blog/article_detail.html
{% extends 'base.html' %}

{% block title %}article_detail{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div name="article" class="col-md-10 col-md-offset-1">
			<h1 class="text-center">{{ article.title }}</h1>
			<p class="blog-post-meta text-center">作者:{{ article.author }}&emsp;发布日期:{{ article.pub_date|date:"Y-m-d" }}&emsp;阅读次数:{{ article.views }}</p>
			<p class="lead" >&emsp;&emsp;{{ article.content |safe }}</p>
		</div>
	</div>
</div>
{% endblock %}

templates/blog/category_detail.html
{% extends 'base.html' %}

{% block title %} {{ category.name }}-insCms {% endblock %}

{% block header %}
<header class="jumbotron subhead" id="header-base">
    <div class="container">
        	<h1>{{ category.name }}-<i><a href="/">home</a></i></h1>
        	<p>{{ category.desc }}</p>
    </div>
</header>
{% endblock %}
{% block content %}
<div class="container">
      <div class="row">
      	{% for article in articles %}
        	<div class="col-md-4">
          	<h2><a href="{% url 'article_detail' %}?id={{ article.id }}">{{ article.title }}</a></h2>
          	<p class="blog-post-meta text-center">作者:{{ article.author }}&emsp;发布日期:{{ article.pub_date|date:"Y-m-d" }}&emsp;阅读次数:{{ article.views }}</p>
          	<p class="lead">&emsp;&emsp;{{ article.content |truncatechars_html:512 |safe}}</p>
          	<p><a class="btn btn-default" href="{% url 'article_detail' %}?id={{ article.id }}" role="button">阅读全文 &raquo;</a></p>
        	</div>
        	{% endfor %}
       </div>
       <div class="row">
       	<div class="col-md-8 col-md-offset-2">
        		<nav>
                        <ul class="pager">
                            {% if articles.has_previous %}
                                <li class="previous"><a
                                        href="?page={{ articles.previous_page_number }}">上一页</a>
                                </li>
                            {% else %}
                                <li class="previous disabled"><a href="#">上一页</a></li>
                            {% endif %}
                            第 {{ articles.number }} / {{ articles.paginator.num_pages }}页
                            {% if articles.has_next %}
                                <li class="next"><a
                                        href="?page={{ articles.next_page_number }}">下一页</a>
                                </li>
                            {% else %}
                                <li class="next disabled"><a href="#">下一页</a></li>
                            {% endif %}
                        </ul>
                    </nav>
           </div>
      </div><!--  /.row -->
    </div>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}insCms{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-8 blog-main">
                {% for article in articles %}
                <div class="blog-post">
                    <h2 class="blog-post-title text-center">
                        <a href="{% url 'article_detail' %}?id={{ article.id }}">{{ article.title }}</a></h2>
                    <p class="blog-post-meta text-center">作者: {{ article.author }}&emsp;发布日期: {{ article.pub_date|date:"Y-m-d" }}&emsp;阅读次数: {{ article.views }}</p>
                    <p class="lead">&emsp;&emsp;{{ article.content |truncatechars_html:512 |safe}}</p>
                    <p><a class="btn btn-default btn-md" role="button" href="{% url 'article_detail' %}?id={{ article.id }}">阅读全文 &raquo;</a></p>
                </div>
                {% endfor %}
                <nav>
                        <ul class="pager">
                            {% if articles.has_previous %}
                                <li class="previous"><a
                                        href="?page={{ articles.previous_page_number }}">上一页</a>
                                </li>
                            {% else %}
                                <li class="previous disabled"><a href="#">上一页</a></li>
                            {% endif %}
                            第 {{ articles.number }} / {{ articles.paginator.num_pages }}页
                            {% if articles.has_next %}
                                <li class="next"><a
                                        href="?page={{ articles.next_page_number }}">下一页</a>
                                </li>
                            {% else %}
                                <li class="next disabled"><a href="#">下一页</a></li>
                            {% endif %}
                        </ul>
                    </nav>
            </div><!-- /.blog-main -->

        <div class="col-sm-4 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>&emsp;&emsp;你好，欢迎光临insCms（内容管理系统）。在这里你可以发布新文章或修改、删除已有的文章。本系统后台使用了Django强大的后台处理。前端使用Bootstrap响应式设计。功能不多，正在继续完善中...</p>
          </div>
          <div>
              <h4>Category</h4>
              <ol class="list-unstyled col-sm-11 col-sm-offset-1">
                {% for category in categorys %}
                <li><a href="{% url 'category_detail' %}/?id={{ category.id }}">{{ category.name }}&nbsp;({{ category.article_set.all.count }})</a></li>
                {% endfor %}
              </ol>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled col-sm-11 col-sm-offset-1">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled col-sm-11 col-sm-offset-1">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->
        </div><!-- /.row -->
    </div><!-- /.container -->
{% endblock %}